name: Build

# Controls when the workflow will run
on: 
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.100'

      - name: Build the solution
        run: dotnet XSB3.0.sln -c Release
        
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          prerelease: true
          tag_name: Test
          name: Pre-Release
          files: /home/runner/work/SB3.0/bin/Release/net6.0/*
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Plugin
          path: /home/runner/work/SB3.0/bin/Release/net6.0/*
